import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Homepage</h1>
      <Link href="/test">This link works (no hard refresh)</Link>
      <br />
      <Link href="/123/test">This link does hard refresh</Link>
      <br />
      <Link href="/541/test">This link does hard refresh</Link>
      <br />
      <Link href="/993/test">This link does hard refresh</Link>
    </>
  )
}
