import Head from 'next/head'
import Link from 'next/link'
import { AppContext } from 'next/app'

interface IProps {
  data: {
    name: string;
  }
}

export default function Home(props: IProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Homepage</h1>
      <Link href="/test">Test</Link>
      {props.data.name}
    </>
  )
}

export async function getStaticPaths() {
  return {
    paths: [{ params: { uid: '1' } }, { params: { uid: '2' } }],
    fallback: 'blocking',
  }
}

// `getStaticPaths` requires using `getStaticProps`
export async function getStaticProps(context: AppContext) {
  const getSomething = await new Promise(resolve => setTimeout(resolve, 250)).then(() => ({
    name: 'cheese'
  }))

  return {
    // Passed to the page component as props
    props: { data: getSomething },
  }
}